.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. dogecash_qt test_dogecash_qt
clean: FORCE
	$(MAKE) -C .. dogecash_qt_clean test_dogecash_qt_clean
check: FORCE
	$(MAKE) -C .. test_dogecash_qt_check
dogecash-qt dogecash-qt.exe: FORCE
	 $(MAKE) -C .. dogecash_qt
